[NoBanner0]
Y=1
[NoBanner1]
Y=42
[NoBanner1a]
Y=27
[NoBanner1b]
Y=30
[NoBanner1c]
Y=32
[NoBanner2]
Y=57
[NoBanner3]
Y=72
[NoBanner3b]
Y=60
[NoBanner3c]
Y=62
[NoBanner4]
Y=87
[NoBanner5]
Y=102
[NoBanner5b]
Y=90
[NoBanner5c]
Y=92

[BarEQ]
X=#EQX#
Y=#EQY#
W=#EQW#
H=#EQH#
BarOrientation=Vertical
AverageSize=5

[Bar1Left]
X=40
Y=102
StringAlign=RightBottom

[Bar1]
X=46
Y=92
W=160
H=6
BarOrientation=Horizontal

[Bar1High]
X=45
Y=90
W=160
H=10
BarOrientation=Horizontal

[Bar1Value]
X=238
Y=102
StringAlign=RightBottom
AutoScale=0

[Bar1ValueHigh]
X=271
Y=102
StringAlign=RightBottom
AutoScale=0

[Bar2Left]
X=40
Y=132
StringAlign=RightBottom

[Bar2]
X=46
Y=122
W=160
H=6
BarOrientation=Horizontal

[Bar2High]
X=45
Y=120
W=160
H=10
BarOrientation=Horizontal

[RPMRight]
X=264

[Bar2Value]
X=238
Y=132
StringAlign=RightBottom
AutoScale=0

[Bar2ValueHigh]
X=271
Y=132
StringAlign=RightBottom
AutoScale=0

[Bar3Left]
X=40
Y=162
StringAlign=RightBottom

[Bar3]
X=46
Y=152
W=160
H=6
BarOrientation=Horizontal

[Bar3High]
X=45
Y=150
W=160
H=10
BarOrientation=Horizontal

[Bar3Value]
X=238
Y=162
StringAlign=RightBottom
AutoScale=0

[Bar3ValueHigh]
X=272
Y=162
StringAlign=RightBottom
AutoScale=0

[Bar4Left]
X=40
Y=192
StringAlign=RightBottom

[Bar4]
X=46
Y=182
W=160
H=6
BarOrientation=Horizontal

[Bar4High]
X=45
Y=180
W=160
H=10
BarOrientation=Horizontal

[Bar4Value]
X=238
Y=192
StringAlign=RightBottom
AutoScale=0

[Bar4ValueHigh]
X=272
Y=192
StringAlign=RightBottom
AutoScale=0

[Title]
X=5
Y=58
StringAlign=LeftTop

[CPULeft]
X=85

[CPUTextBar1Left]
X=71
Y=87
StringAlign=LeftBottom

[TextBar1Left]
X=85
Y=87
StringAlign=LeftBottom

[CPUTextBar1Center]
X=125
Y=87
StringAlign=RightBottom

[TextBar1Center]
X=125
Y=87
StringAlign=RightBottom

[CPURight]
X=165

[CPUTextBar1Right]
X=177
Y=87
StringAlign=RightBottom

[TextBar1Right]
X=165
Y=87
StringAlign=RightBottom

[TextBar2LabelLeft]
X=44
Y=117
StringAlign=LeftBottom

[TextBar2Left]
X=71
Y=117
StringAlign=LeftBottom

[TextBar2Center]
X=125
Y=117
StringAlign=RightBottom

[VMRight]
X=182

[TextBar2Right]
X=177
Y=117
StringAlign=RightBottom

[TextBar3LabelLeft]
X=44
Y=147
StringAlign=LeftBottom

[TextBar3Left]
X=71
Y=147
StringAlign=LeftBottom

[TextBar3Center]
X=125
Y=147
StringAlign=RightBottom

[TextBar3Right]
X=177
Y=147
StringAlign=RightBottom

[TextBar4LabelLeft]
X=44
Y=177
StringAlign=LeftBottom

[TextBar4Left]
X=82
Y=177
StringAlign=LeftBottom

[TextBar4Center]
X=125
Y=177
StringAlign=RightBottom

[TextBar4Right]
X=171
Y=177
StringAlign=RightBottom

[CircleBorderAlign]
X=0
Y=0
W=100
H=100
StartAngle=4.712
RotationAngle=6.283

[CircleBarAlign]
X=0
Y=0
W=100
H=100
StartAngle=2.356
RotationAngle=3.8

[CircleBarLabelAlign]
X=50
Y=70
StringAlign=CenterCenter

[CircleBarValueAlignAS]
X=75
Y=53
StringAlign=CenterCenter
AutoScale=1

[CircleBarValueAlign]
X=72
Y=53
StringAlign=CenterCenter

[CircleBarValueHighAlignAS]
X=50
Y=35
StringAlign=CenterCenter
AutoScale=1

[CircleBarValueHighAlign]
X=53
Y=35
StringAlign=CenterCenter
AutoScale=0

[CircleBarCircle]
X=0
Y=0
W=100
H=100
StartAngle=4.712
RotationAngle=6.283

[CircleGaugeBorder]
X=0
Y=0
W=200
H=50
StringAlign=CenterTop
