[MainLabel]
Meter=String
MeterStyle=TitleLabel|Title
Text=#LabelText#
DynamicVariables=1

[TextMeter1L]
Meter=String
MeterStyle=TextBarValue|TextBar1Left
MeasureName=BaseV
NumOfDecimals=2
Text="%1V"
DynamicVariables=1

[TextMeterDivider1]
Meter=String
MeterStyle=TextBarLabel|TextBar1Center
Text="/"
DynamicVariables=1

[TextMeter1R]
Meter=String
MeterStyle=TextBarValueHigh|TextBar1Right
MeasureName=VHigh
NumOfDecimals=2
Text="(%1V)"
DynamicVariables=1

[TextMeter2LabelLeft]
Meter=String
MeterStyle=TextBarLabel|TextBar2LabelLeft
Text=#LabelText6#
DynamicVariables=1

[TextMeter2bL]
Meter=String
MeterStyle=TextBarValue|TextBar2Left
MeasureName=BaseClock
Text="%1MHz"
DynamicVariables=1

[TextMeterDivider2b]
Meter=String
MeterStyle=TextBarLabel|TextBar2Center
Text="/"
DynamicVariables=1

[TextMeter2bR]
Meter=String
MeterStyle=TextBarValueHigh|TextBar2Right
MeasureName=ClockHigh
Text="(%1MHz)"
DynamicVariables=1

[TextMeter3LabelLeft]
Meter=String
MeterStyle=TextBarLabel|TextBar3LabelLeft
Text=#LabelText7#
DynamicVariables=1

[TextMeter3L]
Meter=String
MeterStyle=TextBarValue|TextBar3Left
MeasureName=BaseMemClock
Text="%1MHz"
DynamicVariables=1

[TextMeterDivider3]
Meter=String
MeterStyle=TextBarLabel|TextBar3Center
Text="/"
DynamicVariables=1

[TextMeter3R]
Meter=String
MeterStyle=TextBarValueHigh|TextBar3Right
MeasureName=MemClockHigh
Text="(%1MHz)"
DynamicVariables=1

[TextMeter4LabelLeft]
Meter=String
MeterStyle=TextBarLabel|TextBar4LabelLeft
Text=#LabelText8#
DynamicVariables=1

[TextMeter4L]
Meter=String
MeterStyle=TextBarValue|TextBar4Left
MeasureName=GPUD3DDyn
Text="%1MB"
DynamicVariables=1

[TextMeterDivider4]
Meter=String
MeterStyle=TextBarLabel|TextBar4Center
Text="/"
DynamicVariables=1

[TextMeter4R]
Meter=String
MeterStyle=TextBarValueHigh|TextBar4Right
MeasureName=GPUD3DDed
Text="(%1MB)"
DynamicVariables=1

