[UsageLabel2]
Meter=String
MeterStyle=BarLabel|Bar2Left
Text=#LabelText3#
DynamicVariables=1

[UsageHighValueBarNeedle2]
Meter=Bar
MeterStyle=BarHighNeedle|Bar2High
MeasureName=RPMHighNeedleAdjust
DynamicVariables=1

[UsageHighValueBar2]
Meter=Bar
MeterStyle=BarHigh|Bar2High
MeasureName=RPMHigh
DynamicVariables=1

[Usage2]
Meter=Bar
MeterStyle=BarRegTempRPM|Bar2
MeasureName=RPMAdjust
DynamicVariables=1

[UsageValue2]
Meter=String
MeterStyle=BarValue|Bar2Value|RPMRight
MeasureName=RPMAdjust
Text="%1 RPM"
AntiAlias=1
DynamicVariables=1

[UsageLabel3]
Meter=String
MeterStyle=BarLabel|Bar3Left
Text=#LabelText4#
DynamicVariables=1

[UsageHighValueBarNeedle3]
Meter=Bar
MeterStyle=BarHighNeedle|Bar3High
MeasureName=UsageHighNeedleAdjust
DynamicVariables=1

[UsageHighValueBar3]
Meter=Bar
MeterStyle=BarHigh|Bar3High
MeasureName=UsageHigh
DynamicVariables=1

[Usage3]
Meter=Bar
MeterStyle=BarRegUsage|Bar3
MeasureName=UsageAdjust
DynamicVariables=1

[UsageValue3]
Meter=String
MeterStyle=BarValue|Bar3Value
MeasureName=BaseUsage
MinValue=0
MAxValue=100
Text="%1%"
DynamicVariables=1

[UsageValueHigh3]
Meter=String
MeterStyle=BarValueHigh|Bar3ValueHigh
MeasureName=UsageHigh
MinValue=0
MaxValue=100
Text="(%1%)"
DynamicVariables=1

[UsageLabel4]
Meter=String
MeterStyle=BarLabel|Bar4Left
Text=#LabelText5#
DynamicVariables=1

[UsageHighValueBarNeedle4]
Meter=Bar
MeterStyle=BarHighNeedle|Bar4High
MeasureName=UsageHighNeedleAdjust
DynamicVariables=1

[UsageHighValueBar4]
Meter=Bar
MeterStyle=BarHigh|Bar4High
MeasureName=UsageHigh
DynamicVariables=1

[Usage4]
Meter=Bar
MeterStyle=BarRegUsage|Bar4
MeasureName=UsageAdjust
DynamicVariables=1

[UsageValue4]
Meter=String
MeterStyle=BarValue|Bar4Value
MeasureName=BaseUsage
MinValue=0
MAxValue=100
Text="%1%"
DynamicVariables=1

[UsageValueHigh4]
Meter=String
MeterStyle=BarValueHigh|Bar4ValueHigh
MeasureName=UsageHigh
MinValue=0
MaxValue=100
Text="(%1%)"
DynamicVariables=1