[MainLabel]
Meter=String
MeterStyle=TitleLabel|Title|NoBanner0
Text=#LabelText#
DynamicVariables=1

[TextMeter3bLabelLeft]
Meter=String
MeterStyle=TextBarLabel|TextBar2LabelLeft|NoBanner2
Text=#LabelText5#
DynamicVariables=1

[TextMeter3bL]
Meter=String
MeterStyle=TextBarValue|TextBar2Left|NoBanner2
MeasureName=VMComm
Text="%1MB"
DynamicVariables=1

[TextMeterDivider3b]
Meter=String
MeterStyle=TextBarValue|TextBar2Center|NoBanner2
Text="/"
DynamicVariables=1

[TextMeter3bR]
Meter=String
MeterStyle=TextBarValue|TextBar2Right|NoBanner2|VMRight
MeasureName=VMAvail
Text="(%1MB)"
DynamicVariables=1

[TextMeter4bLabelLeft]
Meter=String
MeterStyle=TextBarLabel|TextBar3LabelLeft|NoBanner4
Text=#LabelText6#
DynamicVariables=1

[TextMeter4bL]
Meter=String
MeterStyle=TextBarValue|TextBar3Left|NoBanner4
MeasureName=MemUsed
Text="%1MB"
DynamicVariables=1

[TextMeterDivider4b]
Meter=String
MeterStyle=TextBarLabel|TextBar3Center|NoBanner4
Text="/"
DynamicVariables=1

[TextMeter4bR]
Meter=String
MeterStyle=TextBarValue|TextBar3Right|NoBanner4
MeasureName=MemAvail
Text="(%1MB)"
DynamicVariables=1