[UsageLabel2]
Meter=String
MeterStyle=BarLabel|Bar2Left|NoBanner3
Text=#LabelText3#
DynamicVariables=1

[UsageHighValueBarNeedle2]
Meter=Bar
MeterStyle=BarHighNeedle|Bar2High|NoBanner3b
MeasureName=UsageHighNeedleAdjust
DynamicVariables=1

[UsageHighValueBar2]
Meter=Bar
MeterStyle=BarHigh|Bar2High|NoBanner3b
MeasureName=UsageHigh
DynamicVariables=1

[Usage2]
Meter=Bar
MeterStyle=BarRegUsage|Bar2|NoBanner3c
MeasureName=UsageAdjust
DynamicVariables=1

[UsageValue2]
Meter=String
MeterStyle=BarValue|Bar2Value|NoBanner3
MeasureName=BaseUsage
MinValue=0
MaxValue=100
Text="%1%"
DynamicVariables=1

[UsageValueHigh2]
Meter=String
MeterStyle=BarValueHigh|Bar2ValueHigh|NoBanner3
MeasureName=UsageHigh
MinValue=0
MAxValue=100
Text="(%1%)"
DynamicVariables=1


[UsageLabel3]
Meter=String
MeterStyle=BarLabel|Bar3Left|NoBanner5
Text=#LabelText4#
DynamicVariables=1

[UsageHighValueBarNeedle3]
Meter=Bar
MeterStyle=BarHighNeedle|Bar2High|NoBanner5b
MeasureName=UsageHighNeedleAdjust2
DynamicVariables=1

[UsageHighValueBar3]
Meter=Bar
MeterStyle=BarHigh|Bar3High|NoBanner5b
MeasureName=UsageHigh2
DynamicVariables=1

[Usage3]
Meter=Bar
MeterStyle=BarRegUsage|Bar3|NoBanner5c
MeasureName=UsageAdjust2
DynamicVariables=1

[UsageValue3]
Meter=String
MeterStyle=BarValue|Bar3Value|NoBanner5
MeasureName=BaseUsage2
MinValue=0
MaxValue=100
Text="%1%"
DynamicVariables=1

[UsageValueHigh3]
Meter=String
MeterStyle=BarValueHigh|Bar3ValueHigh|NoBanner5
MeasureName=UsageHigh2
MinValue=0
MAxValue=100
Text="(%1%)"
DynamicVariables=1
