;---------------------------------------------------------
;-- OverClock - The Rainmeter Skin for OverClockers.
;---------------------------------------------------------

[Variables]

@IncludeUserSettings=#@#\user_settings.inc
toolTipWidth = 150
toolTipType = 1

[styleBackground]
SolidColor = #userBackgroundColor#

[styleFieldLeft]
FontColor=#userColorField#
FontFace=#userFontName#
FontSize=#userFontSize#
StringAlign=Left
StringEffect=Shadow
AntiAlias=1
ToolTipIcon=INFO
ToolTipType=#toolTipType#
ToolTipWidth=#toolTipWidth#

[styleFieldRight]
FontColor=#userColorField#
FontFace=#userFontName#
FontSize=#userFontSize#
StringAlign=Left
StringEffect=Shadow
AntiAlias=1
ToolTipIcon=INFO
ToolTipType=#toolTipType#
ToolTipWidth=#toolTipWidth#

[styleFieldCenter]
FontColor=#userColorField#
FontFace=#userFontName#
FontSize=#userFontSize#
StringAlign=Center
StringEffect=Shadow
AntiAlias=1
ToolTipIcon=INFO
ToolTipType=#toolTipType#
ToolTipWidth=#toolTipWidth#

[styleLabel]
FontColor=#userColorLabel#
FontFace=#userFontName#
FontSize=#userFontSize#
StringAlign=Left
StringEffect=Shadow
AntiAlias=1
ToolTipIcon=INFO
ToolTipType=#toolTipType#
ToolTipWidth=#toolTipWidth#

[styleLabelRight]
FontColor=#userColorLabel#
FontFace=#userFontName#
FontSize=#userFontSize#
StringAlign=Right
StringEffect=Shadow
AntiAlias=1
ToolTipIcon=INFO
ToolTipType=#toolTipType#
ToolTipWidth=#toolTipWidth#

[styleLabelCenter]
FontColor=#userColorLabel#
FontFace=#userFontName#
FontSize=#userFontSize#
StringAlign=Center
StringEffect=Shadow
AntiAlias=1
ToolTipIcon=INFO
ToolTipType=#toolTipType#
ToolTipWidth=#toolTipWidth#

[styleSettingsLabelRight]
FontColor=#userColorLabel#
FontFace=#userFontName#
FontSize=#userFontSize#
StringAlign=Right
W=200
StringEffect=Shadow
AntiAlias=1
ToolTipIcon=INFO
ToolTipType=#toolTipType#
ToolTipWidth=#toolTipWidth#

[styleSettingsLabelCenter]
FontColor=#userColorLabel#
FontFace=#userFontName#
FontSize=#userFontSize#
StringAlign=Center
W=200
StringEffect=Shadow
AntiAlias=1
ToolTipIcon=INFO
ToolTipType=#toolTipType#
ToolTipWidth=#toolTipWidth#

[styleSettingsLabelLeft]
FontColor=#userColorLabel#
FontFace=#userFontName#
FontSize=#userFontSize#
StringAlign=Left
StringEffect=Shadow
AntiAlias=1
ToolTipIcon=INFO
ToolTipType=#toolTipType#
ToolTipWidth=#toolTipWidth#


[styleFieldAboveBarLeft]
FontColor=#userColorField#
FontFace=#userFontName#
StringAlign=Left
StringEffect=Shadow
FontSize=#userFontSizeAboveBar#
AntiAlias=1
ToolTipIcon=INFO
ToolTipType=#toolTipType#
ToolTipWidth=#toolTipWidth#

[styleFieldAboveBarCenter]
FontColor=#userColorField#
FontFace=#userFontName#
StringAlign=Center
StringEffect=Shadow
FontSize=#userFontSizeAboveBar#
AntiAlias=1
ToolTipIcon=INFO
ToolTipType=#toolTipType#
ToolTipWidth=#toolTipWidth#

[styleFieldAboveBarRight]
FontColor=#userColorField#
FontFace=#userFontName#
StringAlign=Right
StringEffect=Shadow
FontSize=#userFontSizeAboveBar#
AntiAlias=1
ToolTipIcon=INFO
ToolTipType=#toolTipType#
ToolTipWidth=#toolTipWidth#

[styleHorizontalBar]
BarColor=#userColorBarColor#
SolidColor=#userColorBarSolid#
BarOrientation=Horizontal
H=12
W=290
ToolTipIcon=INFO
ToolTipType=#toolTipType#
ToolTipWidth=#toolTipWidth#

[styleVerticalBar]
BarColor=#userColorBarColor#
SolidColor=#userColorBarSolid#
BarOrientation=Vertical
H=12
W=290
ToolTipIcon=INFO
ToolTipType=#toolTipType#
ToolTipWidth=#toolTipWidth#

[styleSideLabel]
FontColor=#userColorSideLabel#
FontFace=#userFontName#
StringEffect=Shadow
FontSize=#userFontSizeSideLabel#
AntiAlias=1
Angle=(Rad(270))
ToolTipIcon=INFO
ToolTipType=#toolTipType#
ToolTipWidth=#toolTipWidth#