[Variables]

; CPU 0
HWiNFO-CPU0-SensorId=0xF0000300
HWiNFO-CPU0-SensorInstance=0x0
HWiNFO-CPU0-Usage=0x7000005

; CPU 0 DTS
HWiNFO-CPU0-DTS-SensorId=0xF0000400
HWiNFO-CPU0-DTS-SensorInstance=0x0
HWiNFO-CPU0-DTS-CoreMax=0x10000ff


; CPU 0 Enhanced
HWiNFO-CPU0-Enhanced-SensorId=0xF0002a00
HWiNFO-CPU0-Enhanced-SensorInstance=0x0
HWiNFO-CPU0-Enhanced-Power=0x5000000

; Motherboard
HWiNFO-MOBO-SensorId=0xf7067760
HWiNFO-MOBO-SensorInstance=0x0
HWiNFO-MOBO-CPU-Fan=0x3000001

; GPU 0
HWiNFO-GPU0-SensorId=0xe0002000
HWiNFO-GPU0-SensorInstance=0x0
HWiNFO-GPU0-Usage=0x7000000
HWiNFO-GPU0-Temp=0x1000000
HWiNFO-GPU0-Fan=0x8000000

; GPU 1
HWiNFO-GPU1-SensorId=0xe0002000
HWiNFO-GPU1-SensorInstance=0x10
HWiNFO-GPU1-Usage=0x7000000
HWiNFO-GPU1-Temp=0x1000000
HWiNFO-GPU1-Fan=0x8000000

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Remote Host 0
HWiNFO-RemoteHost0=0
HWiNFO-RemoteHost1=1
HWiNFO-RemoteHost0-System-SensorId=0xf0000301
HWiNFO-RemoteHost0-System-SensorInstance=0x0

; Remote Host 0 : CPU 0
HWiNFO-RemoteHost0-CPU0-SensorId=0xF0000300
HWiNFO-RemoteHost0-CPU0-SensorInstance=0x1
HWiNFO-RemoteHost0-CPU0-Usage=0x7000009

; Remote Host 0 : CPU 0 DTS
HWiNFO-RemoteHost0-CPU0-DTS-SensorId=0xF0000400
HWiNFO-RemoteHost0-CPU0-DTS-SensorInstance=0x2
HWiNFO-RemoteHost0-CPU0-DTS-CoreMax=0x10000ff

; Remote Host 0 : CPU 0 Enhanced
HWiNFO-RemoteHost0-CPU0-Enhanced-SensorId=0xF0002a00
HWiNFO-RemoteHost0-CPU0-Enhanced-SensorInstance=0x3
HWiNFO-RemoteHost0-CPU0-PackagePower=0x5000000
;HWiNFO-RemoteHost0-CPU0-Enhanced-SensorId=0xF0002a00
;HWiNFO-RemoteHost0-CPU0-Enhanced-SensorInstance=0xb
;WiNFO-RemoteHost0-CPU0-PackagePower=0x5000000


; Remote Host 0 : Motherboard
HWiNFO-RemoteHost0-MOBO-SensorId=0xf001889a
HWiNFO-RemoteHost0-MOBO-SensorInstance=0x5
HWiNFO-RemoteHost0-MOBO-CPU-Fan=0x3000000

; Remote Host 0 : GPU 0
HWiNFO-RemoteHost0-GPU0-SensorId=0xe0002000
HWiNFO-RemoteHost0-GPU0-SensorInstance=0x10
HWiNFO-RemoteHost0-GPU0-Usage=0x7000000
HWiNFO-RemoteHost0-GPU0-Temp=0x1000000
HWiNFO-RemoteHost0-GPU0-Fan=0x3000000
HWiNFO-RemoteHost0-GPU0-Fan1=0x3000000
HWiNFO-RemoteHost0-GPU0-Fan2=0x8000000
HWiNFO-RemoteHost0-GPU0-Power=0x5000000

